### ISSUE TITLE
1.0.0 Master Checklist

### ISSUE THREAD

**Issue by brandonLi8** [brandonLi8/rotational-motion#1]
# Top-level Checklist to be completed for 1.0.0:

## Design
- [x] [Design Document](https://docs.google.com/document/d/1TxJTrQKfupJ5qNxwJuzzzOOyOgG8ufF9V1SH2_Vum-w/edit#) Created (Date: 10/09/2019)
  - [x] Planned [Browser Support](https://docs.google.com/document/d/1TxJTrQKfupJ5qNxwJuzzzOOyOgG8ufF9V1SH2_Vum-w/edit#heading=h.6f9m54dylbfv) (Date: 10/09/2019)
  - [ ] Favicon Created(Date: //)
  - [ ] OG Preview Images (Date: //)
- [ ] Additional Screen Shots (Date: //)

## Implementation
- [x] Repository created (Date: 10/09/2019)
- [x] License added (#2) (Date: 10/10/2019)
- [ ] [Grunt Config](https://github.com/brandonLi8/grunt-config) Added
- [x] Github Project Roadmap completed (Date: 10/10/2019)
- [ ] Code Reviewer Identified and Completed (Date: //)
- [ ] Verify Credits (Date: //)
- [ ] domain/cname confirmed (Date: //)
- [ ] Published! (Date: //)

## Grunt Config
- [x] `npm` initiated with `package.json` (Date: 10/10/2019)
- [x] GitHub labels added (Date: 10/10/2019)
- [ ] `README.md` generated and updated (Date: //)
- [ ] `.gitignore` generated (Date: //)
- [ ] `travis.yml` generated and updated (Date: //)
- [ ] `.wercker.yml` generated and updated (Date: //)

## Testing
- [ ] Performance acceptable on each browser (Date: //)
- [ ] memory leak tested (Date: //)
- [ ] Feature Complete (Date: //)
- [ ] iFrame support tested (Date: //)
- [ ] Embedded link support (Date: //)
